# Generated by Django 3.2.9 on 2021-11-30 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211129_1928'),
        ('authoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.BooleanField(blank=True, default=False, null=True)),
                ('start', models.BooleanField(blank=True, default=False, null=True)),
                ('end', models.BooleanField(blank=True, default=False, null=True)),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='authoring.storypage')),
            ],
            options={
                'verbose_name': 'Story Page',
                'verbose_name_plural': 'Story Pages',
            },
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.CreateModel(
            name='StoryPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(blank=True, default=False, null=True)),
                ('storypage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_page', to='authoring.storypage')),
                ('storypath', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_path', to='authoring.storypage')),
            ],
        ),
        migrations.AddField(
            model_name='storypage',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring.story'),
        ),
    ]
