# Generated by Django 3.2.9 on 2021-12-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0002_auto_20211130_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='extended_object',
        ),
        migrations.RemoveField(
            model_name='story',
            name='public_extension',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='extended_object',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='public_extension',
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='storypage',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
