# Generated by Django 3.2.9 on 2021-12-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211129_1928'),
        ('authoring', '0003_auto_20211201_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storypath',
            unique_together={('storypage', 'storypath')},
        ),
        migrations.CreateModel(
            name='StoryPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='authoring_storypluginmodel', serialize=False, to='cms.cmsplugin')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring.story')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
