# Generated by Django 3.2.9 on 2021-12-03 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211129_1928'),
        ('authoring', '0004_auto_20211201_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypath',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='authoring.story'),
        ),
        migrations.AlterUniqueTogether(
            name='storypath',
            unique_together={('story', 'storypage', 'storypath')},
        ),
        migrations.DeleteModel(
            name='StoryPluginModel',
        ),
    ]
