# Generated by Django 3.2.9 on 2021-12-07 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('authoring', '0005_auto_20211203_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='authors',
            field=models.ManyToManyField(through='authoring.StoryOwner', to='userprofile.Profile'),
        ),
    ]
