# Generated by Django 3.2.9 on 2021-12-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('authoring', '0006_auto_20211207_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyowner',
            options={'verbose_name': 'Story Owner', 'verbose_name_plural': 'Story Owners'},
        ),
        migrations.AddField(
            model_name='story',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_by', to='userprofile.profile', verbose_name='Started by'),
        ),
        migrations.AlterUniqueTogether(
            name='storyowner',
            unique_together={('story', 'user')},
        ),
    ]
