# Generated by Django 3.2.9 on 2021-12-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0007_auto_20211208_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='synopsis',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storypage',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
