# Generated by Django 3.2.9 on 2021-12-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0008_auto_20211209_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyowner',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
