# Generated by Django 3.2.9 on 2021-12-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0009_storyowner_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storypage',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
