# Generated by Django 3.2.9 on 2021-12-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0010_auto_20211210_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
