# Generated by Django 3.2.9 on 2021-12-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0011_storypage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
