# Generated by Django 3.2.9 on 2022-01-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profileconnection'),
        ('authoring', '0012_auto_20211210_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True, max_length=100, null=True)),
                ('start_point', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.profile')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring.storypage')),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True, max_length=100, null=True)),
                ('start_point', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring.comment')),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.profile')),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
    ]
