# Generated by Django 3.2.9 on 2022-01-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0013_comment_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='length',
        ),
        migrations.RemoveField(
            model_name='response',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='response',
            name='start_point',
        ),
    ]
