# Generated by Django 3.2.9 on 2022-01-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0014_auto_20220111_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='start_point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
