# Generated by Django 3.2.9 on 2022-01-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0015_auto_20220114_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authoring.story'),
        ),
        migrations.AddField(
            model_name='response',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authoring.story'),
        ),
    ]
