# Generated by Django 3.2.9 on 2022-01-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0016_auto_20220114_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='resolve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='resolve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
