# Generated by Django 3.2.9 on 2021-12-03 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0023_auto_20211129_1928'),
        ('authoring', '0005_auto_20211203_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='integrations_storypluginmodel', serialize=False, to='cms.cmsplugin')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authoring.story')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
