# Generated by Django 3.2.9 on 2021-12-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0007_auto_20211208_0214'),
        ('cms', '0023_auto_20211129_1928'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypluginmodel',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring.story'),
        ),
        migrations.CreateModel(
            name='StoryOwnerPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='integrations_storyownerpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('storyowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring.storyowner')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
