# Generated by Django 3.2.9 on 2021-12-10 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0012_auto_20211210_2101'),
        ('cms', '0023_auto_20211129_1928'),
        ('integrations', '0002_auto_20211208_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPagePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='integrations_storypagepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('storypage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring.storypage')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
